services:
  - type: web
    name: keycloak-bbda
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: KC_DB_URL
        fromDatabase:
          name: keycloak-db
          property: url   # Render fournit l'URL compl√®te JDBC
      - key: KC_DB_USERNAME
        fromDatabase:
          name: keycloak-db
          property: user
      - key: KC_DB_PASSWORD
        fromDatabase:
          name: keycloak-db
          property: password
      - key: KC_HTTP_PORT
        fromSecret: PORT   # Utiliser fromSecret pour la variable dynamique Render

databases:
  - name: keycloak-db
    plan: free
